// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDktwt2ZvmHKc3wS2pRLIN-4rB3sa93O2o',
    appId: '1:997332879381:web:0967ce511e28f4cb19e61c',
    messagingSenderId: '997332879381',
    projectId: 'loyalapp3-c8940',
    authDomain: 'loyalapp3-c8940.firebaseapp.com',
    databaseURL: 'https://loyalapp3-c8940-default-rtdb.firebaseio.com',
    storageBucket: 'loyalapp3-c8940.appspot.com',
    measurementId: 'G-2PN41V0TLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdf4BU2pRuWC8zMO-88dm4ZUoxzjyTK0U',
    appId: '1:997332879381:android:a98f5b6856e08a1919e61c',
    messagingSenderId: '997332879381',
    projectId: 'loyalapp3-c8940',
    databaseURL: 'https://loyalapp3-c8940-default-rtdb.firebaseio.com',
    storageBucket: 'loyalapp3-c8940.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-47MQtoqPeeP2tm9XalCxEwBrZKNJpKE',
    appId: '1:997332879381:ios:6850d4acd249694b19e61c',
    messagingSenderId: '997332879381',
    projectId: 'loyalapp3-c8940',
    databaseURL: 'https://loyalapp3-c8940-default-rtdb.firebaseio.com',
    storageBucket: 'loyalapp3-c8940.appspot.com',
    iosBundleId: 'com.example.toplulukUygulamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-47MQtoqPeeP2tm9XalCxEwBrZKNJpKE',
    appId: '1:997332879381:ios:6850d4acd249694b19e61c',
    messagingSenderId: '997332879381',
    projectId: 'loyalapp3-c8940',
    databaseURL: 'https://loyalapp3-c8940-default-rtdb.firebaseio.com',
    storageBucket: 'loyalapp3-c8940.appspot.com',
    iosBundleId: 'com.example.toplulukUygulamaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDktwt2ZvmHKc3wS2pRLIN-4rB3sa93O2o',
    appId: '1:997332879381:web:f9f31921c535206219e61c',
    messagingSenderId: '997332879381',
    projectId: 'loyalapp3-c8940',
    authDomain: 'loyalapp3-c8940.firebaseapp.com',
    databaseURL: 'https://loyalapp3-c8940-default-rtdb.firebaseio.com',
    storageBucket: 'loyalapp3-c8940.appspot.com',
    measurementId: 'G-3CL5NHGSWZ',
  );
}
